print("Please fill in the blanks below:")
print("___(name)___'s favorite subject in school is ___(subject)___.")
name = input("What's their name? ")
subject = input("What's the subject? ")
print(name + "'s favorite subject in school is " + subject + ".")